name: Tag & Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build Page
      id: build
      run: |
        cd ./build && npm install && cd ../
        npm install
        npm run build --if-present
    - name: Deploy to Github Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: public
        build_dir: dist
        keep_history: true
        fqdn: beta.metadoc.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
